// <auto-generated />
using System;
using KadinUrunleriSitesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KadinUrunleriSitesi.Migrations
{
    [DbContext(typeof(KadinUrunPlatformuContext))]
    [Migration("20250619151038_ArkadaslikSistemi")]
    partial class ArkadaslikSistemi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Adminler", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminId")
                        .HasName("PK__Adminler__719FE4E8E0366B44");

                    b.ToTable("Adminler", (string)null);
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Arkadaslik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlanId")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GonderenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Arkadasliklar");
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Kategoriler", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KategoriID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KategoriId")
                        .HasName("PK__Kategori__1782CC92B2168735");

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ProfilFotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ProfilFotoURL");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KullaniciId")
                        .HasName("PK__Kullanic__E011F09B982A6ED3");

                    b.HasIndex(new[] { "Email" }, "UQ__Kullanic__A9D105346CD89D1C")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Puanlar", b =>
                {
                    b.Property<int>("PuanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PuanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuanId"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    b.HasKey("PuanId")
                        .HasName("PK__Puanlar__04A64C6E925C743A");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("Puanlar", (string)null);
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Urunler", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("EkleyenKullaniciID");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriID");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ResimURL");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UrunId")
                        .HasName("PK__Urunler__623D364B8D52E8D8");

                    b.HasIndex("EkleyenKullaniciId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler", (string)null);
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Yorumlar", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YorumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YorumId"));

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    b.Property<int>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    b.Property<string>("YorumFotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("YorumFotoURL");

                    b.Property<DateTime?>("YorumTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("YorumId")
                        .HasName("PK__Yorumlar__F2BE14C8ECB0227D");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("Yorumlar", (string)null);
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Puanlar", b =>
                {
                    b.HasOne("KadinUrunleriSitesi.Models.Kullanicilar", "Kullanici")
                        .WithMany("Puanlars")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK__Puanlar__Kullani__4AB81AF0");

                    b.HasOne("KadinUrunleriSitesi.Models.Urunler", "Urun")
                        .WithMany("Puanlars")
                        .HasForeignKey("UrunId")
                        .IsRequired()
                        .HasConstraintName("FK__Puanlar__UrunID__49C3F6B7");

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Urunler", b =>
                {
                    b.HasOne("KadinUrunleriSitesi.Models.Kullanicilar", "EkleyenKullanici")
                        .WithMany("Urunlers")
                        .HasForeignKey("EkleyenKullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK__Urunler__Ekleyen__412EB0B6");

                    b.HasOne("KadinUrunleriSitesi.Models.Kategoriler", "Kategori")
                        .WithMany("Urunlers")
                        .HasForeignKey("KategoriId")
                        .IsRequired()
                        .HasConstraintName("FK__Urunler__Kategor__403A8C7D");

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Yorumlar", b =>
                {
                    b.HasOne("KadinUrunleriSitesi.Models.Kullanicilar", "Kullanici")
                        .WithMany("Yorumlars")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK__Yorumlar__Kullan__45F365D3");

                    b.HasOne("KadinUrunleriSitesi.Models.Urunler", "Urun")
                        .WithMany("Yorumlars")
                        .HasForeignKey("UrunId")
                        .IsRequired()
                        .HasConstraintName("FK__Yorumlar__UrunID__44FF419A");

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Kategoriler", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Kullanicilar", b =>
                {
                    b.Navigation("Puanlars");

                    b.Navigation("Urunlers");

                    b.Navigation("Yorumlars");
                });

            modelBuilder.Entity("KadinUrunleriSitesi.Models.Urunler", b =>
                {
                    b.Navigation("Puanlars");

                    b.Navigation("Yorumlars");
                });
#pragma warning restore 612, 618
        }
    }
}
